apiVersion: v1
kind: Service
metadata:
    name: "aksemea01-5e32"
    labels:
        app: "aksemea01-5e32"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksemea01-5e32"