on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n akscontainer001 -g akscontainer001b35a-rg --location "West Europe" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n akscontainer001 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n akscontainer001 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n akscontainer001 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: akscontainer001.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/complete" -f  "complete/Dockerfile" -t akscontainer001.azurecr.io/aksemea01:${{ github.sha }}
        docker push akscontainer001.azurecr.io/aksemea01:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_aksemea01_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-emea01b9f0 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-emea01b9f0`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-emea01b9f0
        container-registry-url: akscontainer001.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: aksemea01dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-emea01b9f0
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          akscontainer001.azurecr.io/aksemea01:${{ github.sha }}
        imagepullsecrets: |
          aksemea01dockerauth